create table if not exists public.rankings (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 8),
  character text not null,
  score integer not null check (score >= 0),
  round_scores integer[],
  cannon_color text,
  created_at timestamptz not null default now()
);

alter table public.rankings enable row level security;

drop policy if exists rankings_select_public on public.rankings;
drop policy if exists rankings_insert_public on public.rankings;

create policy rankings_select_public
on public.rankings
for select
to anon, authenticated
using (true);

create policy rankings_insert_public
on public.rankings
for insert
to anon, authenticated
with check (
  name is not null
  and character is not null
  and score is not null
  and score >= 0
);

grant select, insert on public.rankings to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
